{{- if eq "true" (include "install-argocd-project" .) }}
{{- $gitopsNamespace := include "get-argocd-namespace" . }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: orchestrator-gitops
  namespace: {{ $gitopsNamespace }}
spec:
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
{{- end }}