{{- $ns := .Values.orchestrator.namespace }}
{{- if .Values.orchestrator.devmode }}
  {{- $namespace := (lookup "v1" "Namespace" "" $ns) }}
  {{- if $namespace }}
# Namespace exist, do nothing.
  {{- else }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    argocd.argoproj.io/managed-by: {{ .Values.argocd.namespace }}
---
  {{- end }}
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
  namespace: {{ $ns }}
spec:
  build:
    template:
      resources:
        requests:
          memory: {{ .Values.orchestrator.sonataPlatform.resources.requests.memory }}
          cpu: {{ .Values.orchestrator.sonataPlatform.resources.requests.cpu }}
        limits:
          memory: {{ .Values.orchestrator.sonataPlatform.resources.limits.memory }}
          cpu: {{ .Values.orchestrator.sonataPlatform.resources.limits.cpu }}
  services:
    dataIndex:
      enabled: true
    jobService:
      enabled: true
---      
{{- else }}
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
  namespace: {{ $ns }}
spec:
  build:
    template:
      resources:
        requests:
          memory: {{ .Values.orchestrator.sonataPlatform.resources.requests.memory }}
          cpu: {{ .Values.orchestrator.sonataPlatform.resources.requests.cpu }}
        limits:
          memory: {{ .Values.orchestrator.sonataPlatform.resources.limits.memory }}
          cpu: {{ .Values.orchestrator.sonataPlatform.resources.limits.cpu }}
  services:
    dataIndex:
      enabled: true
      persistence:
        postgresql:
          secretRef:
            name: {{ .Values.postgres.authSecret.name }}
            userKey: {{ .Values.postgres.authSecret.userKey }}
            passwordKey: {{ .Values.postgres.authSecret.passwordKey }}
          serviceRef:
            name: {{ .Values.postgres.serviceName }}
            namespace: {{ .Values.postgres.serviceNamespace }}
    jobService:
      enabled: true
      persistence:
        postgresql:
          secretRef:
            name: {{ .Values.postgres.authSecret.name }}
            userKey: {{ .Values.postgres.authSecret.userKey }}
            passwordKey: {{ .Values.postgres.authSecret.passwordKey }}
          serviceRef:
            name: {{ .Values.postgres.serviceName }}
            namespace: {{ .Values.postgres.serviceNamespace }}
---
{{- end }}
apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowClusterPlatform
metadata:
  name: cluster-platform
spec:
  platformRef:
    name: sonataflow-platform
    namespace: {{ $ns }}
