architecture: standalone
auth:
  existingSecret: ""  # name of existing secret to use for PostgreSQL credentials. 
  secretKeys:
    userPasswordKey: password  # name of key in existing secret to use for PostgreSQL credentials. Only used when `existingSecret` is set.
  database: sonataflow  # database instance used by data index and job service
  username: postgres  # database user name 
  password: postgres  # database password. Ignored if existingSecret is set.
primary:
  persistence:
    size: 2Gi # the database storage size
  service:
    ports:
      postgresql: 5432  # service port to access the database
# For OpenShift-related configuration see:
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/README.md#differences-between-bitnami-postgresql-image-and-docker-official-image
  podSecurityContext:
    fsGroup: null
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    runAsUser: null
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop: ['ALL']
volumePermissions:
  enabled: false
shmVolume:
  enabled: false