apiVersion: sonataflow.org/v1alpha08
kind: SonataFlowPlatform
metadata:
  name: sonataflow-platform
spec:
  build:
    config:
      strategyOptions:
        KanikoBuildCacheEnabled: "false"
      registry:
        address: quay.io/kiegroup
        secret: regcred
  {{- if (and (.Values.platform.eventing.broker.name) (.Values.platform.eventing.broker.namespace)) }}
  eventing:
    broker:
      ref:
        apiVersion: eventing.knative.dev/v1
        kind: Broker
        name: {{ .Values.platform.eventing.broker.name }}
        namespace: {{ .Values.platform.eventing.broker.namespace }}
  {{- end }}
  services:
    dataIndex:
      enabled: true
      podTemplate:
        container:
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
    jobService:
      enabled: true
      podTemplate:
        container:
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
