includeCustomResources: false  # set to true to have the custom resources (KnativeEventing, KnativeServing, SonataFlow and SonataFlowPlatform).

sonataFlowOperator:
  enabled: true  # whether the operator should be deployed by the chart
  subscription:
    namespace: openshift-operators  # namespace where the operator should be deployed
    channel: alpha  # channel of an operator package to subscribe to
    installPlanApproval: Automatic  # whether the update should be installed automatically
    pkgName: sonataflow-operator  # name of the operator package
    sourceImage: quay.io/masayag/kogito-serverless-operator-catalog:v2.0.0-snapshot  # catalog image of the development build. Unset it for the release build.
    sourceNamespace: openshift-marketplace # namespace of the catalog source
    source: sonataflow-operator  # name of the catalog source for the operator

serverlessOperator:
  enabled: true  # whether the operator should be deployed by the chart
  subscription:
    namespace: openshift-serverless  # namespace where the operator should be deployed
    channel: stable  # channel of an operator package to subscribe to
    installPlanApproval: Automatic  # whether the update should be installed automatically
    pkgName: serverless-operator # name of the operator package
    sourceNamespace: openshift-marketplace # namespace of the catalog source

postgres:
  externalPostgresDBHost: ""  # host name of an existing Postgres DB used by dataindex and job service. If empty, a local Postgres DB is deployed
  existingSecret: ""  # name of existing secret to use for PostgreSQL credentials. 
  secretKeys:
    userPasswordKey: password  # name of key in existing secret to use for PostgreSQL credentials. Only used when `existingSecret` is set.
  database: sonataflow  # database instance used by data index and job service
  username: postgres  # database user name 
  password: postgres  # database password. Ignored if existingSecret is set.
  storage: 2Gi # the database storage size
  serviceName: postgres-db-service # service name to access the database
  port: 5432  # service port to access the database
  dataDir: /var/lib/postgresql/data/dbfiles  # where the database data files are stored inside the container

# override Janus image with one with the orchestrator plugin
backstage:
  global:
    dynamic:
      includes:
        - dynamic-plugins.default.yaml
      plugins:
        - disabled: false
          integrity: >-
            sha512-uwGZRqe0IXFO9Xtsm106FxykFCIIa0htYIbo01yhUx4n2tjz6tvGhKGv7zeVaQYeGJ7AytQ1Y9p/xTHrF1PuZw==
          package: '@caponetto-tests/backstage-plugin-orchestrator-backend-dynamic@0.0.3'
          pluginConfig:
            orchestrator:
              sonataFlowService:
                baseUrl: http://event-timeout.sonataflow-infra.svc.cluster.local
                path: /
              editor:
                path: 'https://sandbox.kie.org/swf-chrome-extension/0.32.0'
        - disabled: false
          integrity: >-
            sha512-re4v8pu+97DEdv3MAELP0iehHSG2HxlmE/JA7Ss/3ZfcM5bcH85DlsLrZS7cGAMiZSkKUn3q9d360pTCyeyasQ==
          package: '@caponetto-tests/backstage-plugin-orchestrator@0.0.3'
          pluginConfig:
            dynamicPlugins:
              frontend:
                caponetto-tests.backstage-plugin-orchestrator:
                  appIcons:
                    - importName: OrchestratorIcon
                      module: OrchestratorPlugin
                      name: orchestratorIcon
                  dynamicRoutes:
                    - importName: OrchestratorPage
                      menuItem:
                        icon: orchestratorIcon
                        text: Orchestrator
                      module: OrchestratorPlugin
                      path: /orchestrator
  upstream:
    backstage:
      image:
        tag: next
      appConfig:
        integrations:
          github:
            - host: github.com
              token: "INSERT VALID TOKEN HERE"
        auth:
          environment: development
          providers:
            github:
              development:
                clientId: "INSERT VALID CLIENT ID HERE"
                clientSecret: "INSERT VALID CLIENT SECRET HERE"
        backend:
          csp:
            frame-src:
              - 'https://sandbox.kie.org'

orchestrator:
  namespace: sonataflow-infra  # namespace where the data index, job service and workflows are deployed
  dataindex:
    image: quay.io/kiegroup/kogito-data-index-postgresql:1.42 # image for data index
    name: data-index-service # service name of the data index
    port: 8080  # service port of the data index
  jobsservice:
    image: quay.io/kiegroup/kogito-jobs-service-postgresql:1.44 # image for job service
    name: jobs-service-service  # service name of the job service
    port: 8080  # service port of the job service
  sonataPlatform:
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  sonataflows: # workflows to get deployed
    - name: event-timeout  # workflow name
      description: Event timeout example on k8s!
      version: 0.0.1  # workflow version
      id: event-timeout  # workflow id
      profile: dev # workflow profile (dev/prod)
      serviceTargetPort: 8080  # workflow service port number
      propsConfigData: |  # if set, overrides the default configmap generated by the operator for the workflow
        application.properties: |
          # Data Index configuration - commented due to dev profile.
          # mp.messaging.outgoing.kogito-processinstances-events.url=http://data-index-service/processes
          # mp.messaging.outgoing.kogito-usertaskinstances-events.url=http://data-index-service/tasks
          # mp.messaging.outgoing.kogito-variables-events.url=http://data-index-service/variables
           quarkus.profile=dev
          # Skip user tasks and variables events sending.
          kogito.events.usertasks.enabled=false
          kogito.events.variables.enabled=false
          quarkus.log.category."io.smallrye.reactive.messaging".level = DEBUG
          quarkus.log.category."org.kie".level = DEBUG
          quarkus.log.category."io.quarkus.reactivemessaging".level = DEBUG
          quarkus.log.category."io.vertx".level = DEBUG
      spec: |+
        flow:
          start: PrintStartMessage
          events:
            - name: event1
              source: ''
              type: event1_event_type
            - name: event2
              source: ''
              type: event2_event_type
          functions:
            - name: systemOut
              type: custom
              operation: sysout
          timeouts:
            eventTimeout: PT60S
          states:
            - name: PrintStartMessage
              type: operation
              actions:
                - name: printSystemOut
                  functionRef:
                    refName: systemOut
                    arguments:
                      message: "${\"event-state-timeouts: \" + $WORKFLOW.instanceId + \" has started.\"}"
              transition: WaitForEvent1
            - name: WaitForEvent1
              type: event
              onEvents:
                - eventRefs: [ event1 ]
                  eventDataFilter:
                    data: "${ \"The event1 was received.\" }"
                    toStateData: "${ .exitMessage1 }"
                  actions:
                    - name: printAfterEvent1
                      functionRef:
                        refName: systemOut
                        arguments:
                          message: "${\"event-state-timeouts: \" + $WORKFLOW.instanceId + \" executing actions for event1.\"}"
              transition: WaitForEvent2
            - name: WaitForEvent2
              type: event
              onEvents:
                - eventRefs: [ event2 ]
                  eventDataFilter:
                    data: "${ \"The event2 was received.\" }"
                    toStateData: "${ .exitMessage2 }"
                  actions:
                    - name: printAfterEvent2
                      functionRef:
                        refName: systemOut
                        arguments:
                          message: "${\"event-state-timeouts: \" + $WORKFLOW.instanceId + \" executing actions for event2.\"}"
              transition: PrintExitMessage
            - name: PrintExitMessage
              type: operation
              actions:
                - name: printSystemOut
                  functionRef:
                    refName: systemOut
                    arguments:
                      message: "${\"event-state-timeouts: \" + $WORKFLOW.instanceId + \" has finalized. \" + if .exitMessage1 != null then .exitMessage1 else \"The event state did not receive event1, and the timeout has overdue\" end + \" -- \" + if .exitMessage2 != null then .exitMessage2 else \"The event state did not receive event2, and the timeout has overdue\" end }"
              end: true