name: Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Orchestartor Helm Lint
        run: |
          cd charts/orchestrator
          helm dep up
          helm lint
      - name: Move2Kube Helm Lint
        run: |
          cd charts/move2kube
          helm dep up
          helm lint
